### ISSUE TITLE
Large numbers with commas cut off at first comma in number_range

### ISSUE THREAD

**Issue by freddaw** [Patrick64/reefine#10]
I am using Reefine on a client site, where one of the text fields used for the number_range has numbers into the tens of thousands to millions, large enough to use commas. However, Reefine is cutting the numbers off at the first comma, so for example, 249,000 displays as 249 in the number_range fields.

I tried changing the text fields to number fields, but it did not make a difference. 

For now, I changed the numbers to omit commas, but it makes it more difficult for customers to quickly read, and our client would prefer that the numbers displayed correctly.

Is there a way to make a change in Reefine to accommodate large numbers with commas in the number_range?

**Comment by freddaw** [comment]
Thanks Patrick for taking the time to update Reefine. It does help, but there is still a small problem that I haven’t been able to overcome.

With the update, the placeholder number still does not have the dollar sign or commas for currency, and the range result after pressing submit does not have the dollar sign. 

I can add the placeholder dollar sign and commas by changing the placeholder code to placeholder="{filter_min:currency currency='USD' decimals='0' locale='en_US'}", and I can add the dollar sign using CSS. But the CSS adds the dollar sign to BOTH the range result and placeholder, leaving double dollar signs for the placeholder.

Would you be able to either have your updated code apply to the placeholder as well as the range result, so that I can use the CSS for the dollar sign for both OR have the range result include the dollar sign, and I can then omit the CSS.

Thanks.

**Comment by Patrick64** [comment]
@freddaw Sure, I'll take a look at it soon

**Comment by Patrick64** [comment]
@freddaw Hi. I've reverted making it format the `{label}` `{filter_max}` and `{filter_min}` so you should be able to put in the `:currency` formatter again. I'm not sure what you mean about the dollar sign though, can you give an example?

**Comment by freddaw** [comment]
@Patrick64 I may not be working on this part of the project going forward, so this issue is on hold for me. But thanks for looking at it.

**Comment by Patrick64** [comment]
@freddaw Great, no problem.
