### ISSUE TITLE
404 Error when using pagination on an entries tag inside reefine tag

### ISSUE THREAD

**Issue by amadeus77** [Patrick64/reefine#13]
When using pagination on an entries tag inside a reefine tag I always get a 404 when going to the "second" page (or further pages in the pagination). I am using the url-method and I think it has something to do with the segment parsing!?

**Comment by Patrick64** [comment]
For anyone else reading this, the issue was using Structure and the problem was fixed using Freebie https://github.com/Patrick64/reefine#structure
