### ISSUE TITLE
Clear button only clearing tree groups, not number range.

### ISSUE THREAD

**Issue by freddaw** [Patrick64/reefine#14]
I’m using Reefine to filter 2 tree groups and one number range, using a custom template based on the Reefine form template. I've added method="ajax" as a parameter in the Reefine tag in the EE template The filtering is working fine with one Search button for all filters, but I also want to clear all of the filters with Ajax as well.
The following button in the form template, clears both tree groups, but not the number range field. I can clear them all if the page refreshes, but I’d like to do it with Ajax.

These are the 2 buttons I have at the bottom of the Reefine custom template based on the Reefine form template. They are located after the tree groups and number range tags.

`<input type="submit" name="submit" id="reefine_submit" value="SEARCH"/>`

`<input type="submit" name="submit" id="{clear_url}" value="CLEAR"/>`

Also, when I change to the default form template, and add the clear button none of the fields cleared, whether the button is within the list_group tags or after.

Thanks for looking.

**Comment by Patrick64** [comment]
@freddaw  The issue is Reefine doesn't actually have a feature to clear all filters. The `{clear_url}` tag is just specific to an individual filter group. However there is a workaround. Any links in the #reefine_sidebar element (`<div id="reefine_sidebar" >`) will be processed as ajax links so you can add a link within there that just points to the search page without any parameters eg `<a href="/{segment_1}/{segment_2}">Clear All</a>` Hope that helps.

**Comment by freddaw** [comment]
@Patrick64 I found that adding `<a href="/{segment_1}/{segment_2}">Clear All</a>` in the shop template works to clear everything as an ajax link, but when using the default form template with that link, no ajax.

**Comment by Patrick64** [comment]
@freddaw Do you mean you're using `theme="form"` and the clear link doesn't work in the #reefine_sidebar div?

**Comment by freddaw** [comment]
@Patrick64 Yes. Same EE template, but with theme="shop", the ajax link works. With theme="form", it doesn't work. The only thing I changed in the form template is to change list_group tags to tree_group tags, and `<div class="reefine_list {group_name}_container">` to `<div class="reefine_tree {group_name}_container">`, plus adding `<a href="/{segment_1}/{segment_2}">Clear All</a>` to both filter_groups.html. 

And I uploaded fresh versions of both /form and /shop to make sure I hadn't made any other changes.

**Comment by Patrick64** [comment]
@freddaw Ok, I see. I think it's because links in the reefine_sidebar aren't ajaxified like in the shop theme. I've added this commit so it should work now  https://github.com/Patrick64/reefine/commit/50eff65ff75e7c3f23a16fb29c6a160aa34146aa

**Comment by freddaw** [comment]
@Patrick64 I made the 3 changes, but still no Ajax response from the link in the /form template that is inside the `<div class="reefine_sidebar" id="reefine_sidebar">`

**Comment by Patrick64** [comment]
@freddaw Ah that's weird. Are you getting any JS errors or anything?

**Comment by freddaw** [comment]
@Patrick64 No errors. To keep it as simple as possible, I removed the layout for the template, but still no Ajax response from the link.

And thinking it might be related to EE5, I installed it on an EE7 site, made the 3 changes, and added the link within `<div class="reefine_sidebar" id="reefine_sidebar"></div>`. Same result.

**Comment by Patrick64** [comment]
@freddaw Not sure. You could modify the javascript to target the link directly using a class or something I guess.
