### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by 5BYFIVE** [Patrick64/reefine#15]
Getting a notice on the front-end when testing on PHP 8.1

Deprecated
preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated
user/addons/reefine/pi.reefine.php, line 1166

Severity: E_DEPRECATED

**Comment by ic360-com** [comment]
I've just stumbled across the same Warnings. Have temporarily downgraded my PHP to 8.0 to avoid it.

**Comment by Patrick64** [comment]
@ic360-com @5BYFIVE That's done I've fixed the warning, if you grab the new version it should be ok now.

**Comment by ic360-com** [comment]
Thanks, that worked.  😄

**Comment by Patrick64** [comment]
@ic360-com Great. Thanks for the sponsor by the way. I can put your logo under sponsors on the readme page if you like?

**Comment by ic360-com** [comment]
Pleasure mate.  Thanks for continuing to support this add-on for the community.  😄 
Yes that'll be great if you're able to add my logo. Thanks very much.

**Comment by Patrick64** [comment]
@ic360-com  Great thanks. I've added your logo! 😀
