### ISSUE TITLE
Using caching breaks the filter URL

### ISSUE THREAD

**Issue by ic360-com** [Patrick64/reefine#16]
I've just tried to enable caching on my EE Template, but the destination URL of the Reefine filter goes to...
https://www.domain.co.uk/jobs?search=&region=east-of-england
...instead of...
https://www.domain.co.uk/jobs/any/east-of-england/any/any

I've tried using EE Template Caching and also the method described in your Docs... both with the same results.
https://github.com/Patrick64/reefine#performance

What could be causing this?
Thanks

**Comment by Patrick64** [comment]
@ic360-com I've tried enabling caching on a template but haven't been able to recreate this issue. Can you post the template code you're using?

**Comment by ic360-com** [comment]
I'll email you the link and code. Thanks.

**Comment by Patrick64** [comment]
@ic360-com Thanks for the code. So I think the issue is it's using a form so when it sends a GET request EE is returning the cached copy of the page rather than the redirect. Try changing it to a POST request, then hopefully EE won't use the cached copy:

```
<form method="post" action="{site_url}{segment_1}">
<input type="hidden" name="XID" value="{XID_HASH}" />  
```

**Comment by ic360-com** [comment]
Ahhh... thanks, that worked.  😄

**Comment by Patrick64** [comment]
@ic360-com Great that's good news.
