### ISSUE TITLE
Ralph Link

### ISSUE THREAD

**Issue by mahuti** [Patrick64/reefine#2]
In your hello world part of the docs it refers to the Ralph Website. The URL has a SQL error http://www.ralphmedia.co.uk/reefine/demo_basic

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'legacy_field_data' in 'field list':
SELECT field_id, field_type, field_name, site_id, field_label, concat('field_id_',field_id) as field_column, 0 as is_title_field, case when legacy_field_data = 'y' then 1 else 0 end as is_legacy_field FROM exp_channel_fields

Thought you might wanna know.

**Comment by Patrick64** [comment]
This is fixed now
