### ISSUE TITLE
Getting an error on front-end where Reefine is in use.

### ISSUE THREAD

**Issue by 5BYFIVE** [Patrick64/reefine#8]
Any ideas? Just moved site to development server and have been updating CMS and plugins.

EE v6.3.2
Reefine 3.2.2

Deprecated
implode(): Passing glue string after array is deprecated. Swap the parameters
user/addons/reefine/pi.reefine.php, line 1138

Severity: E_DEPRECATED

**Comment by Patrick64** [comment]
Probably latest version of PHP needs those parameters swapped for implode. Are you able to do that, then if you can send me a PR I'm happy to merge.

**Comment by Patrick64** [comment]
Nice one, thanks for letting me know.

**Comment by Patrick64** [comment]
Looks like that's already been fixed, I think you were on an old version of Reefine perhaps? https://github.com/Patrick64/reefine/commit/98e411617f29f4e3fc6ee2dd374e079c7617936b

**Comment by 5BYFIVE** [comment]
Ah yea, I had updated to v3.2.2. Looks like that is the version that is on expressionengine.com.

**Comment by Patrick64** [comment]
Ah I see, I think I've forgotten to upload the latest version there. Thanks for letting me know.
